env:
    node: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:jest/recommended
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: latest
plugins:
    - "@typescript-eslint"
    - jest
rules:
    no-shadow: off
    no-constant-condition: off
    "@typescript-eslint/no-shadow":
        - error
    no-use-before-define: off
    "@typescript-eslint/no-use-before-define":
        - error
    "jest/expect-expect": off
